def translate_korean(word):
    # Справочник: корейский -> русский
    dictionary = {
    #-------марки авто-------------
        "현대": "Hyundai",
        "제네시스": "Genesis",
        "기아": "Kia",
        "KG모빌리티(쌍용)": "SsangYong",
    #--------модели huyndai--------
        "그랜저": "Grandeur",
        "아반떼": "Avante (Elantra)",
        "싼타페": "Santa Fe",
        "쏘나타": "Sonata",
        "스타렉스": "Starex",
        "팰리세이드": "Palisade",
        "투싼": "Tucson",
        "스타리아": "Staria",
        "코나": "Kona",
        "아이오닉5": "IONIQ 5",
        "캐스퍼": "Casper",
        "에쿠스": "Equus",
        "벨로스터": "Veloster",
        "엑센트": "Accent",
        "i30": "i30",
        "베뉴": "Venue",
        "맥스크루즈": "Maxcruz (Grand Santa Fe)",
        "i40": "i40",
        "아이오닉": "IONIQ",
        "아이오닉6": "IONIQ 6",
        "쏠라티": "Solati",
        "넥쏘": "NEXO",
        "아슬란": "Aslan",
        "베라크루즈": "Veracruz",
        "갤로퍼": "Galloper",
        "테라칸": "Terracan",
        "투스카니": "Tuscani",
        "다이너스티": "Dynasty",
        "베르나": "Verna",
        "아이오닉9": "IONIQ 9",
        "트라제 XG": "Trajet XG",
        "ST1": "ST1",
        "엑셀": "Excel",
        "티뷰론": "Tiburon",
        "포니": "Pony",
        "라비타": "Lavita",
        "마르샤": "Marcia",
        "엘란트라": "Elantra",
        "산타모": "Santamo",
        "아토스": "Atos",
        "클릭": "Click",
        "프레스토": "Presto",
        "그라나다": "Granada",
        "그레이스": "Grace",
        "블루온": "BlueOn",
        "스쿠프": "Scoupe",
        "스텔라": "Stellar",
        "코티나": "Cortina",
    #--------модели kia--------
        "카니발": "Carnival",
        "쏘렌토": "Sorento",
        "K5": "K5",
        "K7": "K7 (Cadenza)",
        "스포티지": "Sportage",
        "모닝": "Morning (Picanto)",
        "레이": "Ray",
        "K3": "K3 (Forte/Cerato)",
        "K8": "K8",
        "모하비": "Mohave (Borrego)",
        "K9": "K9 (Quoris/K900)",
        "셀토스": "Seltos",
        "니로": "Niro",
        "EV6": "EV6",
        "스팅어": "Stinger",
        "쏘울": "Soul",
        "스토닉": "Stonic",
        "카렌스": "Carens",
        "프라이드": "Pride (Rio)",
        "포르테": "Forte",
        "오피러스": "Opirus (Amanti)",
        "EV3": "EV3",
        "EV9": "EV9",
        "로체": "Lotze",
        "타스만": "Tasman",
        "포텐샤": "Potentia",
        "봉고Ⅲ 미니버스": "Bongo III Minibus",
        "엔터프라이즈": "Enterprise",
        "스펙트라": "Spectra",
        "EV4": "EV4",
        "레토나": "Retona",
        "리갈": "Regal",
        "비스토": "Visto",
        "아벨라": "Avella",
        "엘란": "Elan",
        "캐피탈": "Capital",
        "크레도스": "Credos",
        "파크타운": "Parktown",
        "프레지오": "Pregio",
        "X-TREK": "X-TREK",
        "델타": "Delta",
        "록스타": "Rocsta",
        "리오": "Rio",
        "베스타": "Vesta",
        "브리사": "Brisa",
        "세피아": "Sephia",
        "슈마": "Shuma",
        "쎄라토": "Cerato",
        "씨드": "Ceed",
        "옵티마": "Optima",
        "카스타": "Carstar",
        "콩코드": "Concord",
        "타우너": "Towner",
        "토픽": "Topic",
        "텔루라이드": "Telluride",
        "피아트132": "Fiat 132",
    #------модели SangYang-------
        "렉스턴": "Rexton",
        "타호": "Tahoe",
        "G2X": "G2X",
        "젠트라": "Gentra",
        "토스카": "Tosca",
        "아카디아": "Acadia",
        "티코": "Tico",
        "볼트(Volt)": "Volt",
        "스테이츠맨": "Statesman",
        "윈스톰": "Winstorm",
        "슈퍼살롱": "Super Salon",
        "에스페로": "Espero",
        "레간자": "Leganza",
        "레조": "Rezzo",
        "매그너스": "Magnus",
        "넥시아": "Nexia",
        "누비라": "Nubira",
        "라노스": "Lanos",
        "로얄살롱": "Royal Salon",
        "르망": "LeMans",
        "맵시": "Mapsy",
        "베리타스": "Veritas",
        "브로엄": "Brougham",
        "씨에로": "Cielo",
        "임페리얼": "Imperial",
        "칼로스": "Kalos",
        "콜벳": "Corvette",
        "프린스": "Prince",
    #------Тип топлива--------
        "가솔린": "бензин",
        "디젤": "дизель",
        "가솔린+전기": "гибрид",
        "전기": "электро"
    }

    return dictionary.get(word, word)
